repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: uv run ruff check .
        language: system
        exclude: \.github/.*|\.toml$|\.yaml$|\.yml$|__pycache__|\.pyc$
      - id: pyright
        name: pyright
        entry: uv run pyright
        language: system
        exclude: \.github/.*|\.toml$|\.yaml$|\.yml$|__pycache__|\.pyc$